--Clientes
insert into CLIENTES (NOMBRE_CLI,APELLIDOS_CLI,RUT_CLI,EMAIL_CLI,FECHA_CREACION_CLI,CONTRASEÑA_CLI,TELEFONO_CLI,TIPO_CLI) values ('Matias','Maldonado Oviedo','19504450-3','maldo1514@gmail.com',TO_DATE(SYSDATE),'cliente','+56978851234','E');
--Contratos
insert into CONTRATOS (FECHA_INICIO_CONTRA,FECHA_TERMINO_CONTRA,PDF_CONTRA,TIPO_CONTRA) VALUES (TO_DATE(SYSDATE),TO_DATE(SYSDATE),NULL,'A');
insert into CONTRATOS (FECHA_INICIO_CONTRA,FECHA_TERMINO_CONTRA,PDF_CONTRA,TIPO_CONTRA) VALUES (TO_DATE(SYSDATE),TO_DATE(SYSDATE),NULL,'A');
--PRODUCTORES
insert into PRODUCTORES (NOMBRE_PROD,APELLIDO_PROD,RUT_PROD,EMAIL_PROD,FECHA_CREACION_PROD,CONTRASEÑA_PROD,TELEFONO_PROD,ID_CONTRA) values ('PANCHITO SA',NULL,'72342121-2','panchito@gmail.com',TO_DATE(SYSDATE),'productor','+56987464127',1);
--TRANSPORTISTAS
insert into TRANSPORTISTAS (NOMBRE_TRAN,APELLIDOS_TRAN,RUT_TRAN,EMAIL_TRAN,CAPACIDAD_CARGA, CONTRASÑA_TRAN, FECHA_CREACION, PATENTE, REFRIGERACION, TAMAÑO, TELEFONO_TRAN, ID_CONTRA) VALUES ('Leonardo', 'Barrueto', '194987633', 'reload_13@live.cl', 3.12, '123', TO_DATE(SYSDATE), 'dgrt23', '1', 'Grande', '+56944940903', 2);